from pathlib import Path

from pc_trajectory.traj2_format import (
    Trj2File,
    Trj2Header,
    Trj2LineRecord,
    Trj2PenDownRecord,
    Trj2PenUpRecord,
)
from pc_trajectory.traj2_reader import (
    decode_trj2,
    format_trj2,
    read_trj2,
)
from pc_trajectory.traj2_writer import (
    encode_trj2,
    write_trj2,
)


# Independent frozen fixture. This literal is not generated by the writer.
GOLDEN_TRJ2_BYTES = bytes.fromhex(
    "54524a3202002000070000002c0000000000000000000000000000000000000021000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000009643000000000000c842000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000fa43000000000000484300000000000000000000000000000000000000000000000000000000210000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000096430000000000009643000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
)


def golden_file() -> Trj2File:
    return Trj2File(
        header=Trj2Header(
            start_x_mm=0.0,
            start_y_mm=0.0,
            start_yaw_deg=0.0,
        ),
        records=(
            Trj2PenDownRecord(),
            Trj2LineRecord(
                end_x_mm=100.0,
                end_y_mm=0.0,
                speed_mm_s=300.0,
                acceleration_mm_s2=0.0,
            ),
            Trj2PenUpRecord(),
            Trj2LineRecord(
                end_x_mm=200.0,
                end_y_mm=0.0,
                speed_mm_s=500.0,
                acceleration_mm_s2=0.0,
            ),
            Trj2PenDownRecord(),
            Trj2LineRecord(
                end_x_mm=300.0,
                end_y_mm=0.0,
                speed_mm_s=300.0,
                acceleration_mm_s2=0.0,
            ),
            Trj2PenUpRecord(),
        ),
    )


def test_golden_is_exactly_340_bytes():
    assert len(GOLDEN_TRJ2_BYTES) == 340
    assert 340 == 32 + 7 * 44


def test_golden_writer_matches_independent_bytes_exactly():
    actual = encode_trj2(golden_file())

    assert actual == GOLDEN_TRJ2_BYTES


def test_golden_reader_decodes_independent_fixture():
    decoded = decode_trj2(GOLDEN_TRJ2_BYTES)

    assert decoded.header.start_x_mm == 0.0
    assert decoded.header.start_y_mm == 0.0
    assert decoded.header.start_yaw_deg == 0.0
    assert decoded.record_count == 7

    assert isinstance(decoded.records[0], Trj2PenDownRecord)
    assert isinstance(decoded.records[1], Trj2LineRecord)
    assert isinstance(decoded.records[2], Trj2PenUpRecord)
    assert isinstance(decoded.records[3], Trj2LineRecord)
    assert isinstance(decoded.records[4], Trj2PenDownRecord)
    assert isinstance(decoded.records[5], Trj2LineRecord)
    assert isinstance(decoded.records[6], Trj2PenUpRecord)

    assert decoded.records[1].end_x_mm == 100.0
    assert decoded.records[1].speed_mm_s == 300.0

    assert decoded.records[3].end_x_mm == 200.0
    assert decoded.records[3].speed_mm_s == 500.0

    assert decoded.records[5].end_x_mm == 300.0
    assert decoded.records[5].speed_mm_s == 300.0


def test_golden_writer_reader_round_trip():
    original = golden_file()

    decoded = decode_trj2(encode_trj2(original))

    assert decoded == original


def test_write_and_read_file_round_trip(tmp_path):
    output = tmp_path / "golden.traj"

    returned = write_trj2(golden_file(), output)

    assert returned == output
    assert output.stat().st_size == 340
    assert output.read_bytes() == GOLDEN_TRJ2_BYTES
    assert read_trj2(output) == golden_file()


def test_format_golden_contains_expected_semantics():
    text = format_trj2(golden_file())

    assert "TRJ2 V2" in text
    assert "records=7" in text
    assert "[0] PenDown" in text
    assert "[1] Line" in text
    assert "speed=300.000" in text
    assert "[2] PenUp" in text
    assert "[3] Line" in text
    assert "speed=500.000" in text


def test_golden_travel_is_not_a_distinct_binary_line_type():
    decoded = decode_trj2(GOLDEN_TRJ2_BYTES)

    # Record 1 and record 3 are both ordinary LINE.
    # Draw-vs-travel semantics come from pen state, not from LINE type.
    assert type(decoded.records[1]) is Trj2LineRecord
    assert type(decoded.records[3]) is Trj2LineRecord


def test_golden_header_uses_record_count_semantics():
    file = golden_file()

    assert file.record_count == 7
    assert not hasattr(file, "segment_count")
